username: "{{ lookup('env', 'USER') }}"
home: /home/{{ lookup('env', 'USER') }}

packages_apt:
  - copyq
  - curl
  - fwupd
  - git
  - unrar
  - net-tools
  - python3-pip
  - software-properties-common
  - wget
  - zsh

packages_pip:
  - ansicolors
  - kubernetes
  - requests
  - schema

packages_snap: [ ]


# k8s packages
kops_version: 1.22.5
kubectl_version: 1.23.13
kubelogin_version: 1.25.1
istioctl_version: 1.11.8
meshctl_version: 1.1.2
helm_version: 3.9.3
kustomize_version: 4.0.4

targzs:
  toolbox:
    name: "Jetbrains toolbox"
    url: "https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.22.10774.tar.gz"
    target_dir: "{{ home }}"
    original_dir: "jetbrains-toolbox-1.22.10774"
    symlinked_dir: "jetbrains-toolbox"

binaries:
  docker_compose:
    name: docker-compose
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    zsh_completion: https://raw.githubusercontent.com/docker/compose/$(docker-compose --version | awk 'NR==1{print $NF}')/contrib/completion/zsh/_docker-compose


sdkman_script_install_url: http://get.sdkman.io
sdk_java_versions:
  - 8.0.292.hs-adpt
  - 11.0.11.hs-adpt
  - 16.0.2-temq

nvm_version: 0.39.0
nvm_node_versions:
  - 16.9.1