username: "{{ lookup('env', 'USER') }}"
home: /home/{{ lookup('env', 'USER') }}

packages_apt:
  - wget
  - copyq
  - curl
  - fwupd
  - git
  - zip
  - unrar
  - unzip
  - net-tools
  - python3-pip
  - software-properties-common

packages_snap: []

# k8s packages
kops_version: 1.22.5
kubectl_version: 1.23.13
kubelogin_version: 1.25.1
istioctl_version: 1.11.8
helm_version: 3.9.3
kustomize_version: 4.0.4

targzs:
  toolbox:
    name: "Jetbrains toolbox"
    url: "https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.22.10774.tar.gz"
    target_dir: "{{ home }}"
    original_dir: "jetbrains-toolbox-1.22.10774"
    symlinked_dir: "jetbrains-toolbox"

binaries:
  docker_compose:
    name: docker-compose
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    zsh_completion: https://raw.githubusercontent.com/docker/compose/$(docker-compose --version | awk 'NR==1{print $NF}')/contrib/completion/zsh/_docker-compose

oh_my_zsh_version: 0.9.20
