---
- name: Configuring Local Environment - Asus Zenbook 13
  hosts: all
  connection: local
  environment:
    NETRC: "/dev/null"
  roles:
    - role: base
    #    - role: bartdorlandt.ohmyzsh
    #    - role: gantsign.sdkman
    - role: docker
    - role: k8s_tools
    #    - role: ms-teams
    - role: slack
    - role: vscode
  handlers:
    - name: Restart Galaxy
      supervisorctl:
        name: galaxy
        state: restarted
      listen: restart galaxy
