---
- name: run playbook tasks locally
  hosts: 127.0.0.1
  connection: local
  environment:
    NETRC: '/dev/null'
  roles:
    - role: base
  tasks:
    - include_tasks: playbooks/targz-apps.yml
    - include_tasks: playbooks/docker.yml
