---
- name: Configuring Local Environment - El_Giancar
  hosts: all
  connection: local
  environment:
    NETRC: "/dev/null"
  roles:
    - role: base
    - role: ohmyzsh
    - role: topgrade
    - role: docker
    - role: k8s_tools
    - role: vscode
  handlers:
    - name: Restart Galaxy
      supervisorctl:
        name: galaxy
        state: restarted
      listen: restart galaxy
