---
- name: Configuring Local Environment - Asus Zenbook 13
  hosts: all
  connection: local
  environment:
    NETRC: "/dev/null"
  roles:
    - role: base
    - role: ohmyzsh
    - role: vscode
    - role: docker
    - role: k8s_tools
  handlers:
    - name: Restart Galaxy
      supervisorctl:
        name: galaxy
        state: restarted
      listen: restart galaxy
