---
- hosts: all
  tasks:
    - include: playbooks/apt.yml
    - include: playbooks/targz-apps.yml
    - include: playbooks/docker.yml
    # - include: playbooks/oh-my-zsh.yml
    # - include: playbooks/nvm_node.yml
    # - include: playbooks/sdkman_java.yml