---
- name: Microsoft Visual Studio Code
  include_role:
    name: custom_apt
    apply:
      tags:
        - vscode
    public: no
  vars:
    name: vscode
    key:
      id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
      url: https://packages.microsoft.com/keys/microsoft.asc
      keyring: /etc/apt/trusted.gpg.d/packages.microsoft.gpg
    arch: amd64
    repo: https://packages.microsoft.com/repos/code stable main
    package: code
  tags:
    - vscode
