---
- name: Slack
  include_role:
    name: custom_apt
    apply:
      tags:
        - slack
    public: no
  vars:
    name: slacktechnologies_slack
    key:
      id: DB085A08CA13B8ACB917E0F6D938EC0D038651BD
      url: https://packagecloud.io/slacktechnologies/slack/gpgkey
      keyring: /etc/apt/trusted.gpg.d/slacktechnologies_slack.gpg
    repo: https://packagecloud.io/slacktechnologies/slack/debian/ jessie main
    package: slack-desktop
  tags:
    - slack
