---
- name: Microsoft Teams
  include_role:
    name: custom_apt
    apply:
      tags:
        - teams
    public: no
  vars:
    name: teams
    key:
      id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
      url: https://packages.microsoft.com/keys/microsoft.asc
      keyring: /etc/apt/trusted.gpg.d/packages.microsoft.gpg
    arch: amd64
    repo: https://packages.microsoft.com/repos/ms-teams/dists stable main
    package: teams
  tags:
    - teams
