---
# Install APT packages
- name: Install APT packages
  become: true
  apt:
    name: "{{ packages_apt }}"
    update_cache: yes
  tags:
    - apt

# Install SNAP packages
- name: Install SNAP packages
  become: true
  snap:
    name: "{{ packages_snap }}"
    classic: yes
  tags:
    - snap
